---
name: AdvancedSudo
version: 1.0.0
author: imlucki
main: imlucki\AdvancedSudo\Loader
api: 5.15.0

permissions:
  AdvancedSudo.sudo.command:
    default: op
    description: "Allows you to use /sudo"
  AdvancedSudo.sudoall.command:
    default: op
    description: "Allows you to use /sudoall"
...
