---
name: AdvancedSudo
version: 1.0.0
author: imLuckii
main: imLuckii\AdvancedSudo\Loader
api: 5.15.0

permissions:
  advancedsudo.command.sudo:
    default: op
    description: "Allows you to use /sudo"
  advancedsudo.command.sudoall:
    default: op
    description: "Allows you to use /sudoall"
...
