---
name: AdvancedSudo
version: 2.0.0
author: imluckii
main: imLuckii\AdvancedSudo\Loader
api: 5.16.0

permissions:
  advancedsudo.command.sudo:
    default: op
    description: "Allows you to use /sudo"
  advancedsudo.command.sudoall:
    default: op
    description: "Allows you to use /sudoall"
...
